//! Provider-abstracted media generation (dev-plan/40).
//!
//! Tier 1 (this slice): images only — a provider trait
//! ([`provider::ImageProvider`]) with Gemini + OpenAI backends, a
//! [`registry`] that maps a model string to its provider, and shared
//! output helpers. The `TextToImage` / `ImageToImage` tools in
//! `tools/image_gen.rs` and (Tier 3) the Media Studio shell both drive
//! generation through this module, so a generation triggered by the
//! model and one triggered from the GUI are byte-identical and bill
//! identically.
//!
//! Tier 2 (video: `VideoProvider` + the async submit/poll job model) and
//! Tier 3 (the Studio shell) build on this seam — see dev-plan/40.

pub mod job;
pub mod provider;
pub mod providers;
pub mod registry;

pub use provider::{
    ImageProvider, ImageRequest, ImageResult, InputImage, JobState, VideoProvider, VideoRequest,
};

use crate::error::{Error, Result};
use sha2::{Digest, Sha256};
use std::path::PathBuf;

/// Detect image format from magic bytes. Generated bytes aren't always
/// PNG (Gemini flash often returns JPEG); mislabelling JPEG as PNG makes
/// Anthropic reject the inline image block.
pub fn sniff_ext(bytes: &[u8]) -> &'static str {
    if bytes.starts_with(&[0x89, b'P', b'N', b'G']) {
        "png"
    } else if bytes.starts_with(&[0xFF, 0xD8, 0xFF]) {
        "jpg"
    } else if bytes.len() > 11 && &bytes[8..12] == b"WEBP" {
        "webp"
    } else {
        "png"
    }
}

/// Save image bytes under `output/img-<ts>-<sha8>.<ext>` and return the
/// relative path. Creates `output/` if missing; the sha prefix makes
/// collisions vanishingly unlikely so we never overwrite.
pub fn save_image(bytes: &[u8], ext: &str) -> Result<PathBuf> {
    let sha = Sha256::digest(bytes);
    let sha_hex = format!("{:02x}{:02x}{:02x}{:02x}", sha[0], sha[1], sha[2], sha[3]);
    let ts = chrono::Utc::now().format("%Y%m%d-%H%M%S");
    let name = format!("img-{ts}-{sha_hex}.{ext}");
    let dir = std::path::Path::new("output");
    std::fs::create_dir_all(dir).map_err(|e| Error::Tool(format!("mkdir output: {e}")))?;
    let path = dir.join(&name);
    std::fs::write(&path, bytes)
        .map_err(|e| Error::Tool(format!("write {}: {e}", path.display())))?;
    Ok(path)
}

/// Detect video container from magic bytes. Veo returns MP4 (ISO-BMFF:
/// `....ftyp` at offset 4); fall back to mp4.
pub fn sniff_video_ext(bytes: &[u8]) -> &'static str {
    if bytes.len() > 11 && &bytes[4..8] == b"ftyp" {
        "mp4"
    } else if bytes.starts_with(&[0x1A, 0x45, 0xDF, 0xA3]) {
        "webm"
    } else {
        "mp4"
    }
}

/// Save video bytes under `output/vid-<ts>-<sha8>.<ext>` and return the
/// relative path. Same convention as [`save_image`].
pub fn save_video(bytes: &[u8], ext: &str) -> Result<PathBuf> {
    let sha = Sha256::digest(bytes);
    let sha_hex = format!("{:02x}{:02x}{:02x}{:02x}", sha[0], sha[1], sha[2], sha[3]);
    let ts = chrono::Utc::now().format("%Y%m%d-%H%M%S");
    let name = format!("vid-{ts}-{sha_hex}.{ext}");
    let dir = std::path::Path::new("output");
    std::fs::create_dir_all(dir).map_err(|e| Error::Tool(format!("mkdir output: {e}")))?;
    let path = dir.join(&name);
    std::fs::write(&path, bytes)
        .map_err(|e| Error::Tool(format!("write {}: {e}", path.display())))?;
    Ok(path)
}
